[2023-09-21] Metric
RecoRecoNi/Tech-Interview pull request #22
Opened 2023-09-21 04:10 UTC by Woo-Yeol

### PR Summary

9월 19일 화요일 진행한 스터디 중 Metric 에 대한 부분을 정리했습니다.

피드백 부탁드립니다!

2023-09-21 15:56 UTC, zsmalla approved these changes
정리하시느라 고생 많으셨습니다. 내용상으로 문제가 될 부분은 없어 보이고, 전반적으로 코드블럭과 Latex 수식 부분을 수정 할 필요가 있어보입니다. 해당 부분에 코멘트 달아두었으니 시간 되실 때 반영 부탁드릴게요!

2023-09-21 15:56 UTC, zsmalla commented on 07-ML & DL/Metric.md
> +> `Precision은 모델의 입장`에서, 그리고 `Recall은 실제 정답(data)의 입장`에서 정답을 정답이라고 맞춘 경우를 바라보고 있습니다.
코드 블럭은 키워드 위주로 두면 좋을 것 같아요!

2023-09-21 15:56 UTC, zsmalla commented on 07-ML & DL/Metric.md
> +    ex) 우리가 추천한 아이템 개수 : 5(K)
여기 줄바꿈이 제대로 반영 안되어있는 것 같습니다!

2023-09-21 15:56 UTC, zsmalla commented on 07-ML & DL/Metric.md
> +  $$
여기 수식이 제대로 변환되지 않았습니다!

2023-09-23 07:28 UTC, ksumini commented
우열님, 전체적으로 수정했으면 하는 부분이
정의되는 단어 키워드에만 코드블럭처리하고 내용이나 설명에서 강조되는 부분은 bold처리하는게 가독성있고 일관성 측면에서 좋을 것 같아요! 수정했으면 하는 부분에 대해 남겼습니다~!!

내용이 길어서 작성하시는데 오랜 시간 걸리셨을텐데 한번만 다시 전체적으로 검토 부탁드립니다ㅜㅜ 감사합니다~!!!

2023-09-23 07:28 UTC, ksumini requested changes

2023-09-23 07:28 UTC, ksumini commented on 07-ML & DL/Metric.md
> +1. Precision(정밀도)
우열님, 전체적으로 키워드 단어에 ``로 블록처리를 하는게 좋아보여요!
`Precision(정밀도)` 이런식으로요!!

2023-09-23 07:28 UTC, ksumini commented on 07-ML & DL/Metric.md
> +**Positive 정답률**, **PPV(Positive Predictive Value)** 라고도 불립니다.
이 부분 Precision에 해당하는 내용인데 줄바꿈을 수정하면 더 좋을 것 같습니다!! precision 내용 아래로 들어가게요!

2023-09-23 07:28 UTC, ksumini commented on 07-ML & DL/Metric.md
> +> `Precision은 모델의 입장`에서, 그리고 `Recall은 실제 정답(data)의 입장`에서 정답을 정답이라고 맞춘 경우를 바라보고 있습니다.
저도 내용 강조 부분은 코드 블럭말구 bold 처리가 더 좋을 것 같아요!! 이 밑에 부분들도 전체적으로요..!!

2023-09-23 07:28 UTC, ksumini commented on 07-ML & DL/Metric.md
> +
우열님 이 부분에 </br> 하나 추가해주시면 좋을 것 같습니다!!
회귀 metric 나오다가 바로 밑에 붙어있어서 이어지는 내용 같아요..!

2023-09-23 07:28 UTC, ksumini commented on 07-ML & DL/Metric.md
> +추천 시스템의 성능을 평가하는 데에 사용되는 대표적인 방법들을 살펴보았습니다.
이 부분도 위에 **추천 시스템의 평가 지표**랑 이어져서 다음 줄에 작성되게 해주시면 좋을 것 같습니다~~~!!

2023-09-23 07:28 UTC, ksumini commented on 07-ML & DL/Metric.md
> +   2. 품질 관점
이 부분들도 다 연관성, 다양성, 새로움, 참신함만 코드블럭처리하고 나머지 강조부분은 bold처리하면 보기 더 좋을 것 같아요~

2023-09-23 07:28 UTC, ksumini commented on 07-ML & DL/Metric.md
> +
여기 </br> 하나 있으면 좋을 것 같습니다~!

2023-09-23 07:28 UTC, ksumini commented on 07-ML & DL/Metric.md
> +  사용자의 영화 시청 이력 데이터를 바탕으로 사용자가 다음에 시청할 영화 및 좋아할 영화를 예측
우열님 이 부분도 다 이어서 써져서 다음 문장에

사용자의 영화 시청 이력 데이터를 바탕으로 사용자가 다음에 시청할 영화 및 좋아할 영화를 예측하는 태스트입니다.


이렇게 써주시면 좋을 것 같아요!

2023-09-23 07:28 UTC, ksumini commented on 07-ML & DL/Metric.md
> +  사용자의 책 평점 데이터를 바탕으로 사용자가 어떤 책을 더 선호할지 예측하는 태스크입니다.
이 부분도 다음 문장으로 내려주세요~!!!

2023-09-23 07:28 UTC, ksumini commented on 07-ML & DL/Metric.md
> +  - 평점 예측에서 자주 사용되는 지표 중 하나인 **RMSE (Root Mean Square Error)**를 사용
**RMSE(Root Mean Square Error)** 를 사용

이런식으로 **뒤에 를을 띄워써줘야 bold처리가 잘 적용될 것 같습니다~!!

2023-09-25 15:13 UTC, Woo-Yeol commented
@ksumini @zsmalla 피드백 모두 반영 완료했습니다!

2023-09-25 16:10 UTC, ksumini commented
@Woo-Yeol 고생하셨습니다 우열님..!!! ㅠㅠ 감사합니다~!!

2023-09-25 16:11 UTC, ksumini approved these changes

2023-09-26 06:52 UTC, Woo-Yeol commented
> @Woo-Yeol 고생하셨습니다 우열님..!!! ㅠㅠ 감사합니다~!!

오 아닙니다 늦어서 죄송하죠 ㅎㅎ

2023-09-26 11:40 UTC, merged